ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'SHARK';
ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'PI42';
ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'MUDREX';

ALTER TABLE "exchange_credential"
  ADD COLUMN "tradeCurrency" TEXT NOT NULL DEFAULT 'USDT',
  ADD COLUMN "settings" JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN "lastCheckedAt" TIMESTAMP(3);
